FROM python:3.9

WORKDIR /app

RUN apt-get update && apt-get install -y ffmpeg && apt-get clean

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 5000

# 7. Specify the command to run the Flask app
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
